### ISSUE TITLE
Does this external support building on Windows and/or Linux or is syphon OSX-specific?

### ISSUE THREAD

**Issue by pd-l2ork** [Syphon/PureData#2]
Title says it all. If it supports all three platforms, I would like to package it with Pd-L2Ork, which grew out of Pd-Extended. See https://bit.ly/pd-l2ork for more info. Thanks.

**Comment by vade** [comment]
macOS only.

**Comment by pd-l2ork** [comment]
Thanks. Is this a limitation of the syphon framework, or just this project?

**Comment by vade** [comment]
Syphon. Please check out the Syphon project page for info: https://syphon.github.io

**Comment by pd-l2ork** [comment]
Cool, thanks.
